version: '3.8'

services:
  # migration:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.migration
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_PORT=3306
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_DATABASE=mydb
  #   depends_on:
  #     - mysql
  app:
    build: .
    command: bun start
    x-develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git
            - node_modules
        - action: rebuild
          path: package.json
      ports:
        - 3000:3000
    ports:
      - 3000:3000
    depends_on:
      # - migration
      - mysql
  mysql:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password # deprecated
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb

    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql